name: Java CI Independent Jobs Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build (compile)
        run: mvn clean compile

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build and Run Unit Tests
        run: mvn clean test
      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: target/surefire-reports/

  jacoco:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build, Run Tests, Generate JaCoCo Report
        run: mvn clean test jacoco:report
      - name: Upload JaCoCo HTML-Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  mutation-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build & Mutation Coverage
        run: mvn clean test-compile org.pitest:pitest-maven:mutationCoverage
      - name: Upload PIT Report
        uses: actions/upload-artifact@v4
        with:
          name: pit-report
          path: target/pit-reports/